-- =========================================================
-- Order Items
-- Stores the individual menu items included in an order.
--
-- Price and cost are saved as snapshots so historical
-- reports remain accurate even if the menu item is edited
-- later.
-- =========================================================

create table public.order_items (
  id uuid primary key default gen_random_uuid(),

  -- Parent order this item belongs to.
  -- If the order is deleted, its item rows are deleted too.
  order_id uuid not null
    references public.orders(id)
    on delete cascade,

  -- Original menu item.
  --
  -- If the menu item is deleted later, the historical
  -- order item remains because its name/price/cost snapshot
  -- is stored below.
  menu_item_id uuid
    references public.menu_items(id)
    on delete set null,

  -- Snapshot of the menu item's name at the time of sale.
  item_name varchar not null,

  -- Number of units sold.
  quantity integer not null,

  -- Selling price per unit at the time of the order.
  unit_price numeric(12,2) not null,

  -- Cost per unit at the time of the order.
  -- Nullable because some menu items may not have
  -- a cost price configured.
  unit_cost numeric(12,2),

  -- Total selling amount for this line.
  -- Example:
  -- quantity = 2
  -- unit_price = 250
  -- line_total = 500
  line_total numeric(12,2) not null,

  created_at timestamptz not null default now(),

  -- Quantity must always be at least 1.
  constraint order_items_quantity_positive
    check (quantity > 0),

  -- Monetary values cannot be negative.
  constraint order_items_unit_price_non_negative
    check (unit_price >= 0),

  constraint order_items_unit_cost_non_negative
    check (unit_cost is null or unit_cost >= 0),

  constraint order_items_line_total_non_negative
    check (line_total >= 0),

  -- Keep the stored line total consistent with
  -- quantity × unit price.
  constraint order_items_line_total_matches_calculation
    check (line_total = quantity * unit_price)
);


-- =========================================================
-- Indexes
-- =========================================================

-- Used whenever all items for an order are loaded.
create index order_items_order_id_idx
  on public.order_items (order_id);


-- Useful for menu performance analytics such as
-- quantity sold and revenue generated by an item.
create index order_items_menu_item_id_idx
  on public.order_items (menu_item_id);